name: StreamForge-DEV

services:
  adminer:
    image: adminer:latest

    restart: unless-stopped

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    platform: linux/amd64
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet